ci:
  skip: [stylua]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: file-contents-sorter
        args: [--unique]
        files: .gitignore
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.1
    hooks:
      - id: stylua
  - repo: local
    hooks:
      - id: compile_renovate
        name: compile renovate.json5
        language: python
        types: [lua]
        entry: python3 compile_renovate.py
        additional_dependencies:
          [
            "slpp",
            "json5",
            "jsonata-python",
            "pdbpp",
            "pybars3",
            "more_itertools",
          ]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.32.2
    hooks:
      - id: renovate-config-validator
        args: [--strict]
