name: Check config
on: push

env:
  FORCE_COLOR: 1

jobs:
  check_renovate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
      - run: npm install -g renovate@latest
      - run: renovate-config-validator --strict renovate.json5

  emmylua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: LuaLS/LLS-Addons
          path: LLS-Addons
          # submodules: true
      - run: git submodule init LLS-Addons/luvit
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: Install emmylua
        run: |
          mkdir -p build/emmylua
          curl -L -o emmylua.tar.gz https://github.com/EmmyLuaLs/emmylua-analyzer-rust/releases/download/0.17.0/emmylua_check-linux-x64.tar.gz
          tar -xzf emmylua.tar.gz -C build/emmylua
      - name: Run emmylua
        env:
          LLS_Addons: ${{ github.workspace }}/LLS-Addons
        run: |
          export VIMRUNTIME="$(nvim --headless --cmd 'echo $VIMRUNTIME' +q 2>&1)"
          ./build/emmylua/emmylua_check --config=config/nvim/.emmyrc.json config/nvim/

  check:
    runs-on: ubuntu-latest

    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}/config

    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: uv run compile_renovate.py
      - name: setup
        run: nvim --headless +qa
      - name: restore
        run: nvim --headless "+Lazy! restore" +qa
      - name: clean
        run: nvim --headless "+Lazy! clean" +qa
      - name: lsp
        run: nvim --headless "+LspInfo" +qa
      - uses: nickcharlton/diff-check@main
        with:
          command: |
            git -c color.ui=always diff --word-diff
      - name: dump machine readable diff
        if: always()
        run: |
          # echo "```diff" >> $GITHUB_STEP_SUMMARY
          git diff >> $GITHUB_STEP_SUMMARY
          # echo "```" >> $GITHUB_STEP_SUMMARY
