name: Check config
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      XDG_CONFIG_HOME: ${{ github.workspace }}/config

    steps:
      - uses: actions/checkout@v5
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
      - run: |
          sudo apt update
          sudo apt install neovim
      - run: uv run compile_renovate.py
      - name: setup
        run: nvim --headless +qa
      - name: restore
        run: nvim --headless "+Lazy! restore" +qa
      - name: clean
        run: nvim --headless "+Lazy! clean" +qa
      - name: lsp
        run: nvim --headless "+LspInfo" +qa
      - uses: nickcharlton/diff-check@main
        with:
          command: |
            git -c color.ui=always diff --word-diff
            echo "```diff" >> $GITHUB_STEP_SUMMARY
            git diff >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
